blog/urls.py
from django.conf.urls import include,url
from django.contrib import admin
from . import views
urlpatterns = [
    url(r'^$', views.post_list, name='post_list'),
    url(r'^post/(?P<pk>[0-9]+)/$', views.post_detail, name='post_detail'),
    url(r'^post/new/$', views.post_new, name='post_new'),
    url(r'^post/(?P<pk>\d+)/edit/$', views.post_edit, name='post_edit'),
    url(r'^post_data_input/$', views.post_data_input, name='post_data_input'),
    url(r'^post_result1/$', views.post_data_input, name='post_data_input'),
]

mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('blog.urls')),
]

blog/models.py
from django.db import models
from django.utils import timezone

class Post(models.Model):
    author = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(
            default=timezone.now)
    published_date = models.DateTimeField(
            blank=True, null=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title


ALCOHOL_CHOICES =(
    (1, '알콜성 간염'),
    (0, '정상')
)

SMOKE_CHOICES =(
    (1, '비흡연'),
    (2, '금연'),
    (3, '흡연')
)
GEN_CHOICES = (
    (1, '남'),
    (2, '여')
)

LOC_CHOICES = (
    (11,'서울'),(26,'부산'),(27,'대구'),(29,'인천'),(30,'대전'),(31,'울산'),(36,'세종'),
    (41,'경기도'),(42,'강원도'),(43,'충북'),(44,'충남'),(45,'전북'),(46,'전남'),
    (47,'경북'),(48,'경남'),(49,'제주')
)

class M1_Train_data(models.Model):
    bmi = models.FloatField(null=True, blank=True)
    location = models.CharField(choices=LOC_CHOICES, max_length=20, default="서울")
    triglycerides = models.FloatField(null=True, blank=True)
    hdl = models.FloatField(null=True, blank=True)  # min: 1, max: 97, mean: 56.790048
    ldl = models.FloatField(null=True, blank=True)  # min: -12.2, max: 204.0, mean: 113.38690240000004
    sex = models.PositiveSmallIntegerField(choices=GEN_CHOICES, default="남")  # min: 1, max: 2, mean: 1.499904
    waist = models.FloatField(null=True, blank=True)  # min: 48, max: 166, mean: 79.958884
    systolic_pressure = models.FloatField(null=True, blank=True)  # min: 70, max: 236, mean: 121.438776
    diastolic_pressure = models.FloatField(null=True, blank=True)  # min: 39, max: 151, mean: 75.451088
    fbs = models.FloatField(null=True, blank=True)  # min: 18, max: 685, mean: 98.937808
    old = models.PositiveSmallIntegerField(null=True, blank=True)  # min: 5, max: 18, mean: 10.421392
    smoke = models.PositiveSmallIntegerField(choices=SMOKE_CHOICES,default="금연")  # min: 1, max: 3, mean: 1.57258
    alcohol_hepatitis = models.PositiveSmallIntegerField(choices=ALCOHOL_CHOICES,default="정상")  # min: 0, max: 1, mean: 0.041848

    def __str__(self):
        return self.location

blog/forms.py
from django import forms
from .models import Post
from .models import M1_Train_data
class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ('title', 'text',)

class M1_dataForm(forms.ModelForm):
    class Meta:
        model = M1_Train_data
        fields =['bmi','location','triglycerides','hdl','ldl','sex','waist',
                 'systolic_pressure','diastolic_pressure','fbs','old','smoke',
                 'alcohol_hepatitis',]
        labels = {'bmi' : 'BMI 지수',
                  'location' : '시도코드',
                  'triglycerides' : '트리글리세라이드',
                  'hdl': 'HDL 지수',
                  'ldl': 'LDL 지수',
                  'sex': '성별',
                  'waist': '허리둘레',
                  'systolic_pressure': '수축기 혈압',
                  'diastolic_pressure': '이완기 혈압',
                  'fbs': '공복혈당 지수',
                  'old': '연령',
                  'smoke': '흡연 상태',
                  'alcohol_hepatitis':'알콜성 감염 여부', }

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.utils import timezone
from .models import Post
from .forms import PostForm
from .forms import M1_dataForm
from django.shortcuts import redirect
from .disease_risk import init_risk
from .test import test_model
from django.shortcuts import render
import pandas as pd

def post_detail(request, pk):
    post = get_object_or_404(Post, pk=pk)
    return render(request, 'blog/post_detail.html', {'post': post, 'train_datas':train_datas})

def post_list(request):
    posts = Post.objects.filter(published_date__lte=timezone.now()).order_by('published_date')
    risk_data = init_risk()
    a,b,c,d,e = risk_data['이상지질혈증 위험도(총콜)'][0], risk_data['이상지질혈증 위험도(트리)'][0], risk_data['이상지질혈증 위험도(HDL)'][0],risk_data['이상지질혈증 위험도(LDL)'][0], risk_data['이상지질혈증 위험도'][0]
    f,g,h,i,j = risk_data['이상지질혈증 위험도(총콜)'][1], risk_data['이상지질혈증 위험도(트리)'][1], risk_data['이상지질혈증 위험도(HDL)'][1], risk_data['이상지질혈증 위험도(LDL)'][1], risk_data['이상지질혈증 위험도'][1]
    k,l,m,n,o = risk_data['이상지질혈증 위험도(총콜)'][2], risk_data['이상지질혈증 위험도(트리)'][2], risk_data['이상지질혈증 위험도(HDL)'][2], risk_data['이상지질혈증 위험도(LDL)'][2], risk_data['이상지질혈증 위험도'][2]

    return render(request, 'blog/post_list.html', {'posts': posts ,'a':a,'b':b,'c':c,'d':d,'e':e,'f':f,'g':g,'h':h,'i':i,'j':j,'k':k,'l':l,'m':m,'n':n,'o':o,'risk_data':risk_data})

    #의사결정트리 예제
    #train_Accuracy_Data,test_Accuracy_Data = init_data()
    #return render(request, 'blog/post_list.html', {'posts': posts,'train_Accuracy_Data':train_Accuracy_Data,'test_Accuracy_Data':test_Accuracy_Data})

def post_new(request):
    if request.method == "POST":
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.published_date = timezone.now()
            post.save()
            return redirect('post_detail', pk=post.pk)
    else:
        form = PostForm()
    return render(request, 'blog/post_edit.html', {'form': form})

def post_edit(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == "POST":
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.published_date = timezone.now()
            post.save()
            return redirect('post_detail', pk=post.pk)
    else:
        form = PostForm(instance=post)
    return render(request, 'blog/post_edit.html', {'form': form})

def post_data_input(request):
    if request.method == "POST":
        form = M1_dataForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.save()

            raw_data = {'BMI' : [post.bmi],
                        '시도코드' : [post.location],
                        '트리글리세라이드' : [post.triglycerides],
                        'HDL콜레스테롤' : [post.hdl],
                        'LDL콜레스테롤' : [post.ldl],
                        '식전혈당(공복혈당)' : [post.fbs],
                        '성별코드' : [post.sex],
                        '허리둘레' : [post.waist],
                        '수축기혈압': [post.systolic_pressure],
                        '이완기혈압': [post.diastolic_pressure],
                        '연령대코드(5세단위)': [post.old // 5],
                        '흡연상태': [post.smoke],
                        '알콜성간염여부' :[post.alcohol_hepatitis],
                        }
            data = pd.DataFrame(raw_data)
            a,b,c= test_model(data)
            mx = int(max(a,b,c))
            return render(request, 'blog/post_result1.html', {'a':a,'b':b,'c':c,'mx':mx})
    else:
        form = M1_dataForm()
    return render(request, 'blog/post_data_input.html',{'form':form})

blog/templates/blog/base.html
{% load static %}
<html>
    <head>
        <title>빅데이터 2조 가즈아ㅏㅏ</title>
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
        <link href='//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
        <link rel="stylesheet" href="{% static 'css/blog.css' %}">
    </head>
    <body>
        <div class="page-header">
            {% if user.is_authenticated %}
                <a href="{% url 'post_new' %}" class="top-menu"><span class="glyphicon glyphicon-plus"></span></a>
            {% endif %}
            <h1><a href="/">빅데이터 2조 가즈아ㅏㅏ</a></h1>
                <a href="{% url 'post_data_input' %}">데이터 입력</a>
        </div>
        <div class="content container">
            <div class="row">
                <div class="col-md-8">
                {% block content %}
                {% endblock %}
                </div>
            </div>
        </div>
    </body>
</html>

blog/templates/blog/post_data_input.html
<!DOCTYPE html>
{% load staticfiles %}
{% load static %}
<html lang="ko">
<head>
  <!-- Theme Made By www.w3schools.com - No Copyright -->
  <title>AI big data 2조</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="https://fonts.googleapis.com/css?family=Nanum+Gothic" rel="stylesheet">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
  <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
  <style>
  body {
    font-family: 'Nanum Gothic', sans-serif;
    line-height: 1.8;
    color: #f5f6f7;
  }
  p {font-size: 16px;}
  .margin {margin-bottom: 45px;}
  .bg-1 {
    background-color: #417690; /* Green */
    color: #000000;
  }
  .bg-2 {
    background-color: #474e5d; /* Dark Blue */
    color: #000000;
  }
  .bg-3 {
    background-color: #474e5d; /* White */
    color: #555555;
  }
  .bg-4 {
    background-color: #2f2f2f; /* Black Gray */
    color: #fff;
  }
  .container-fluid {
    padding-top: 70px;
    padding-bottom: 70px;
  }
  .navbar {
    padding-top: 15px;
    padding-bottom: 15px;
    border: 0;
    border-radius: 0;
    margin-bottom: 0;
    font-size: 12px;
    letter-spacing: 5px;
  }
  .navbar-nav  li a:hover {
    color: #1abc9c !important;
  }
  </style>
</head>

<body>

<!-- Navbar -->
<nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">AI · Big data B반 2조</a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav navbar-right">

      </ul>
    </div>
  </div>
</nav>


<div class="container" id="container1">
        <div class="row centered-form">
            <div class="col-xs-12 col-sm-8 col-md-6 col-sm-offset-2 col-md-offset-3">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h2 class="panel-title text-center">정보를 입력해 주세요</h2>
                    </div>
                    <div class="panel-body">
                        <form method="POST" class="post-form">{% csrf_token %}
                            <div class="form-group">
                                <div class ="col-xs-6 col-sm-6 col-md-6">
                                    <label for="id_bmi"><font color ="black">BMI 지수</font></label>
                                    <input type="number" name="bmi" required id="id_bmi" class="form-control input-sm" placeholder="BMI를 입력해주세요.">
                                </div>
                            </div>


                            <div class="form-group">
                                <div class ="col-xs-6 col-sm-6 col-md-6">
                                <label for="id_location"><font color ="black">지역</font></label>
                                <select name="location" id="id_location" class="form-control input-sm">
                                 <option value="11">서울</option>
                                  <option value="26">부산</option>
                                  <option value="27">대구</option>
                                  <option value="29">인천</option>
                                  <option value="30">대전</option>
                                  <option value="31">울산</option>
                                  <option value="36">세종</option>
                                  <option value="41">경기도</option>
                                  <option value="42">강원도</option>
                                  <option value="43">충북</option>
                                  <option value="44">충남</option>
                                  <option value="45">전북</option>
                                  <option value="46">전남</option>
                                  <option value="47">경북</option>
                                  <option value="48">경남</option>
                                  <option value="49">제주</option>
                                </select>
                                </div>
                            </div>


                            <div class="row">
                                <div class="col-xs-6 col-sm-6 col-md-6">
                                    <div class="form-group">
                                        <label for="id_triglycerides"><font color ="black">트리글리세라이드</font></label>
                                        <input type="number" name="triglycerides" required id="id_triglycerides" class="form-control input-sm" placeholder="트리글리세라이드를 입력해주세요.">
                                    </div>
                                </div>
                                <div class="col-xs-6 col-sm-6 col-md-6">
                                    <div class="form-group">
                                        <label for="id_hdl"><font color ="black">HDL 지수</font></label>
                                        <input type="number" name="hdl" required id="id_hdl" class="form-control input-sm" placeholder="HDL 콜레스테롤을 입력해주세요.">
                                    </div>
                                </div>
                            </div>


                            <div class="row">
                                <div class="col-xs-6 col-sm-6 col-md-6">
                                    <div class="form-group">
                                        <label for="id_ldl"><font color ="black">HDL 지수</font></label>
                                        <input type="number" name="ldl" required id="id_ldl" class="form-control input-sm" placeholder="LDL 콜레스테롤을 입력해주세요.">
                                    </div>
                                </div>
                                <div class="col-xs-6 col-sm-6 col-md-6">
                                    <div class="form-group">
                                        <label for="id_sex"><font color ="black">성별</font></label>
                                        <select name="sex" id="id_sex" class="form-control input-sm">
                                            <option value="1">남</option>
                                            <option value="2">여</option>
                                        </select>
                                    </div>
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-xs-6 col-sm-6 col-md-6">
                                    <div class="form-group">
                                        <label for="id_waist"><font color ="black">허리둘레</font></label>
                                        <input type="number" name="waist" required id="id_waist" class="form-control input-sm" placeholder="허리둘레(cm)">
                                    </div>
                                </div>
                                <div class="col-xs-6 col-sm-6 col-md-6">
                                    <div class="form-group">
                                        <label for="id_fbs"><font color ="black">공복혈당 지수:</font></label>
                                        <input type="number" name="fbs" required id="id_fbs" class="form-control input-sm" placeholder="LDL 공복혈당을 입력해주세요.">
                                    </div>
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-xs-6 col-sm-6 col-md-6">
                                    <div class="form-group">
                                        <label for="id_systolic_pressure"><font color ="black">수축기 혈압</font></label>
                                        <input type="number" name="systolic_pressure" required id="id_systolic_pressure" class="form-control input-sm" placeholder="수축기 혈압을 입력해주세요.">
                                    </div>
                                </div>
                                <div class="col-xs-6 col-sm-6 col-md-6">
                                    <div class="form-group">
                                        <label for="id_diastolic_pressure"><font color ="black">이완기 혈압</font></label>
                                        <input type="number" name="diastolic_pressure" required id="id_diastolic_pressure" class="form-control input-sm" placeholder="이완기 혈압을 입력해주세요.">
                                    </div>
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-xs-6 col-sm-6 col-md-6">
                                    <div class="form-group">
                                        <label for="id_smoke"><font color ="black">흡연 상태</font></label>
                                        <select name="smoke" id="id_smoke" class="form-control input-sm">
                                            <option value="1">비흡연</option>
                                            <option value="2">금연</option>
                                            <option value="3">흡연</option>
                                        </select>
                                    </div>
                                </div>
                                <div class="col-xs-6 col-sm-6 col-md-6">
                                    <div class="form-group">
                                        <label for="id_alcohol_hepatitis"><font color ="black">음주성 간염 상태</font></label>
                                        <select name="alcohol_hepatitis" id="id_alcohol_hepatitis" class="form-control input-sm">
                                            <option value="0">정상</option>
                                            <option value="1">알콜성 간염</option>
                                        </select>
                                    </div>
                                </div>
                            </div>

                             <div class="row">
                                <div class="col-xs-6 col-sm-6 col-md-6">
                                    <div class="form-group">
                                        <label for="id_old"><font color ="black">나이</font></label>
                                        <input type="number" name="old" required id="id_old" class="form-control input-sm" placeholder="수축기 혈압을 입력해주세요.">
                                    </div>
                                </div>
                             </div>
                            <button type="submit" class="btn btn-info btn-block">제출</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

<style>
#container1 {
    background-color: #ffffff;
}

.centered-form {
    margin-top: 120px;
    margin-bottom: 120px;
}

.centered-form .panel {
    background: rgba(255, 255, 255, 0.8);
    box-shadow: rgba(0, 0, 0, 0.3) 20px 20px 20px;
}
</style>


</body>
</html>

blog/templates/blog/post_detail.html
{% extends 'blog/base.html' %}

{% block content %}
    <div class="post">
        {% if post.published_date %}
            <div class="date">
                {{ post.published_date }}
            </div>
        {% endif %}
        {% if user.is_authenticated %}
            <a class="btn btn-default" href="{% url 'post_edit' pk=post.pk %}"><span class="glyphicon glyphicon-pencil"></span></a>
        {% endif %}<h1>{{ post.title }}</h1>
        <p>{{ post.text|linebreaksbr }}</p>
    </div>
{% endblock %}

blog/templates/blog/post_edit.html
{% extends 'blog/base.html' %}

{% block content %}

    <div class = "container content">
    </div>
    <h1>글쓰기</h1>
    <form method="POST" class="post-form">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Save</button>
    </form>
{% endblock %}

blog/templates/blog/post_list.html
{% extends 'blog/base.html' %}

{% block content %}

<html>
<head>
  <meta charset="utf-8">
  <title>Django Highcharts Example</title>
</head>
<body>
  <div id="container"></div>
  <script src="https://code.highcharts.com/highcharts.src.js"></script>
<script>
Highcharts.chart('container', {
    chart: {
        type: 'pie',
        options3d: {
            enabled: true,
            alpha: 45,
            beta: 0
        }
    },
    title: {
        text: '당뇨병 환자 비율'
    },
    tooltip: {
        pointFormat: '{series.name}: <b>{point.percentage:.1f}%</b>'
    },
    plotOptions: {
        pie: {
            allowPointSelect: true,
            cursor: 'pointer',
            depth: 35,
            dataLabels: {
                enabled: true,
                format: '{point.name}'
            }
        }
    },
    series: [{
        type: 'pie',
        name: 'Browser share',
        data: [
            ['Firefox', 45.0],
            ['IE', 26.8],
            {
                name: 'Chrome',
                y: 12.8,
                sliced: true,
                selected: true
            },
            ['당뇨병 환자', 6.228],
            ['정상', 93.7]
        ]
    }]
});
</script>
</body>
</html>

        <h1>Decision_Tree</h1>
        <div class = "Accuracy_Data">
            <table class = "table table-striped">
                <thead>
                <tr>
                    <td><B>Training 정확도</B></td>
                    <td><B>Test 정확도</b></td>
                </tr>
                </thead>

                <tbody>
                <tr>
                    <td> {{train_Accuracy_Data}}%</td>
                    <td>{{test_Accuracy_Data}}%</td>
                </tr>
                </tbody>
            </table>
        </div>
    {% for post in posts %}
        <div class="post">
            <div class="date">
                {{ post.published_date }}
            </div>
            <h1><a href="{% url 'post_detail' pk=post.pk %}">{{ post.title }}</a></h1>
            <p>{{ post.text|linebreaksbr }}</p>
        </div>


    {% endfor %}
<p>{{risk_data}}</p>
{% endblock %}